export const routes = {
  main: "/",
  login: "/login",
  register: "/register",
  invoices: "/invoices",
  invoicesDetails: "/invoices/:invoiceId/",
  invoicesAddNew: "/invoices/add_new/",
  suppliers: "/suppliers",
  shipments: "/shipments",
  addNewShipments: "/shipments/add_new",
  orders: "/orders",
  ordersDetails: "/orders/:orderId/",
  addNewOrders: "/orders/add_new",
  users: "/users",
  profile: "/profile",
  machinery: "/machinery",
  machineryProblems: "/machinery/problems",
  machineryTasks: "/machinery/tasks",
  machineryDetails: "/machinery/:machineryId/",
  machineryAddProblem: "/machinery/add_problem/:machineryId/",
  addNewMachinery: "/machinery/add_new",
  machineryTaskDetails: "/machinery/task/:taskId/",
  machineryAddTask: "/machinery/add_task/:machineryId/",
};
